# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unusual', models.BooleanField(verbose_name='특수케이스')),
                ('date', models.DateField(default='1996-02-25', verbose_name='날짜')),
                ('weekday', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금')], default='월', max_length=30, verbose_name='요일')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, verbose_name='교시')),
                ('subject', models.CharField(choices=[('과학', '과학'), ('국어', '국어'), ('기술가정', '기술가정'), ('도덕', '도덕'), ('동아', '동아'), ('미술', '미술'), ('사회', '사회'), ('수학', '수학'), ('스포츠', '스포츠'), ('역사', '역사'), ('영어', '영어'), ('예체', '예체'), ('음악', '음악'), ('주제', '주제'), ('진로', '진로'), ('창체', '창체'), ('철학', '철학'), ('체육', '체육'), ('한문', '한문')], max_length=30, verbose_name='과목')),
                ('teacher', models.CharField(choices=[('강학주', '강학주'), ('김미경', '김미경'), ('김준영', '김준영'), ('김지인', '김지인'), ('김한나', '김한나'), ('김홍진', '김홍진'), ('도레미', '도레미'), ('배근아', '배근아'), ('송유경', '송유경'), ('오인애', '오인애'), ('유세정', '유세정'), ('이경희', '이경희'), ('이득효', '이득효'), ('임성오', '임성오'), ('장윤일', '장윤일'), ('장현선', '장현선'), ('정성진', '정성진'), ('조은숙', '조은숙'), ('조은희', '조은희'), ('조진향', '조진향'), ('최춘호', '최춘호'), ('현미숙', '현미숙')], max_length=30, verbose_name='선생님')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='학년')),
                ('division', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='반')),
                ('classroom', models.CharField(choices=[('---1층---', '---1층---'), ('시청각실', '시청각실'), ('농구장', '농구장'), ('운동장', '운동장'), ('---2층---', '---2층---'), ('기술가정실', '기술가정실'), ('컴퓨터실', '컴퓨터실'), ('과학실1', '과학실1'), ('강당', '강당'), ('우정반', '우정반'), ('---3층---', '---3층---'), ('3-1', '3-1'), ('3-2', '3-2'), ('3-3', '3-3'), ('도서실', '도서실'), ('인사랑1', '인사랑1'), ('인사랑2', '인사랑2'), ('인사랑3', '인사랑3'), ('---4층---', '---4층---'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-3', '2-3'), ('동아리실1', '동아리실1'), ('동아리실2', '동아리실2'), ('Wee 클래스', 'Wee 클래스'), ('과학실2', '과학실2'), ('English Studio', 'English Studio'), ('---5층---', '---5층---'), ('1-1', '1-1'), ('1-2', '1-2'), ('미술실', '미술실'), ('음악실', '음악실'), ('수사랑1', '수사랑1'), ('수사랑2', '수사랑2'), ('역사랑', '역사랑'), ('진로상담실', '진로상담실'), ('--알수없음--', '--알수없음--')], default='--알수없음--', max_length=100, verbose_name='교실')),
                ('start', models.TimeField(default='09:00', verbose_name='시작시간')),
                ('end', models.TimeField(default='09:01', verbose_name='종료시간')),
            ],
        ),
    ]
