# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='unusual',
        ),
        migrations.AddField(
            model_name='timetable',
            name='default',
            field=models.BooleanField(default=False, verbose_name='기본값'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '봄'), (2, '가을')], default=2, verbose_name='학기'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017, verbose_name='년도'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='종료시간'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='시작시간'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.CharField(blank=True, choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금')], max_length=30, verbose_name='요일'),
        ),
    ]
